name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 8 * * *'  
  workflow_dispatch:  # Manual trigger button
    inputs:
      SCOPE:
        description: 'Test scope to run'
        required: false
        default: 'full'
        type: choice
        options:
          - api
          - e2e
          - full
      RUN_ARGS:
        description: 'Additional arguments for the test run'
        required: false
        default: ''
        type: string
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      env:
        SCOPE: ${{ github.event.inputs.SCOPE }}
        RUN_ARGS: ${{ github.event.inputs.RUN_ARGS }}
      run: |
        echo "Running tests with scope: $SCOPE"
        if [ "${{ github.event_name }}" == "schedule" ]; then
          npx playwright test
        else if [ "$SCOPE" == "api" ]; then
          npx playwright test --project api
        else if [ "$SCOPE" == "e2e" ]; then
          npx playwright test --project e2e
        else if [ -n "$RUN_ARGS" ]; then
          npx playwright test $RUN_ARGS
        else if [ -n "$RUN_ARGS" ]; then
          npx playwright test $RUN_ARGS
        else
          npx playwright test
        fi

    - name: Upload Playwright Report as Artifact
      if: ${{ !cancelled() }} # runs the step even if previous steps failed, but skips it if the workflow was manually cancelled.
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    - name: Upload Playwright Report to GitHub Pages
      if: ${{ !cancelled() }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report/
    - name: Deploy to GitHub Pages
      if: ${{ !cancelled() }}
      uses: actions/deploy-pages@v4
      id: deployment
    - name: Display report URL
      if: ${{ !cancelled() }}
      run: echo "ðŸ“Š Test Report is available at ${{ steps.deployment.outputs.page_url }}"

permissions:
  contents: read
  pages: write
  id-token: write
